# Generated by Django 2.2.6 on 2023-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndeedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('job_url', models.CharField(max_length=500)),
                ('job_id', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
